/**
 * Phase 11 (Tier 4 - Evidence-Grounded AI Interpretation).
 *
 * Duck-typed subset of @cma/db's DigestResult/DigestItem (packages/db/src/
 * repositories/intelligence.ts) - same rationale as buildContext.ts's
 * ChangeEventForAnalysis: this package must stay usable without a
 * database dependency, so it never imports @cma/db's Prisma-adjacent
 * types directly. @cma/db's actual DigestResult/DigestItem are
 * structurally compatible with these interfaces and are passed in
 * as-is by callers in packages/db and apps/worker.
 */
export interface DigestItemForInterpretation {
  kind: "CHANGE_EVENT" | "REPEATED_PRICE_CHANGE" | "ACTIVITY_PATTERN" | "SUSTAINED_ACTIVITY_TREND" | "LIFECYCLE";
  competitorId: string;
  competitorName: string;
  detectedAt: Date | string;
  changeEventIds: string[];

  // CHANGE_EVENT
  changeEventId?: string;
  changeType?: string;
  severity?: string;
  /** Deterministically generated by @cma/core's describeChangeEvent - NOT raw webpage content, but may embed page-derived values (a price, a product label) and is treated as untrusted for prompt-construction purposes regardless. */
  description?: string;

  // REPEATED_PRICE_CHANGE / ACTIVITY_PATTERN share a `pattern` bag; kept
  // as plain optional fields here (rather than importing patterns.ts's
  // types) to stay duck-typed and dependency-free.
  pattern?: {
    // RepeatedPriceChangePattern fields
    monitoredUrlId?: string;
    entityKey?: string;
    label?: string | null;
    changeCount?: number;
    qualifies?: boolean;
    firstChangeAt?: Date | string | null;
    lastChangeAt?: Date | string | null;
    // ActivityPattern fields
    competitorId?: string;
    current?: number;
    baselineAverage?: number | null;
    qualifyingWindows?: number;
    direction?: "ABOVE_BASELINE" | "BELOW_BASELINE" | "AT_BASELINE" | "INSUFFICIENT_HISTORY";
    ratio?: number | null;
    strongEvidence?: boolean;
    // shared
    days?: number;
  };

  // SUSTAINED_ACTIVITY_TREND (Phase 16) - additive, optional fields exactly
  // as pre-specified by PHASE14A-HISTORICAL-INTELLIGENCE-DESIGN-AUDIT.md
  // Section 12 and confirmed by PHASE15-INTELLIGENCE-VALUE-AUDIT.md Section
  // 16 item 5: no new claim-safety category, no new evidence type - just
  // these two deterministic numbers/enums, both independently
  // reconstructible from @cma/db's SustainedActivityTrend.lookback.
  consecutiveQualifyingWindows?: number;
  direction?: "ABOVE_BASELINE" | "BELOW_BASELINE";

  // LIFECYCLE
  added?: number;
  removed?: number;
}

export interface DigestForInterpretation {
  days: number;
  windowStart: Date | string;
  windowEnd: Date | string;
  totalTrackedCompetitors: number;
  items: DigestItemForInterpretation[];
  crossCompetitorContext: {
    aboveBaselineCount: number;
    totalTrackedCompetitors: number;
  };
}

/**
 * Section 11 of the brief: the bounded, structured input actually sent
 * to the model. Deliberately smaller/flatter than DigestForInterpretation
 * itself - only what buildDigestUserPrompt needs, already truncated and
 * capped (see digestLimits.ts / buildDigestContext.ts).
 */
export interface EvidenceBundleItem {
  /** Stable id the model must cite verbatim if referencing this item - one of the competitor's own changeEventIds, never invented. */
  evidenceChangeEventIds: string[];
  kind: DigestItemForInterpretation["kind"];
  detectedAt: string;
  /**
   * Trusted, deterministic, numeric/structural summary of this item -
   * see buildDigestContext.ts's fieldsForItem(). Free-text fields that
   * ultimately originate from a monitored competitor page (a product
   * label, a price string, the auto-generated change description) are
   * kept in `untrustedText`, never here.
   */
  facts: Record<string, string | number | boolean | null>;
  /** Page-derived free text for this item (may be empty) - always rendered inside the prompt's <UNTRUSTED_WEB_CONTENT> block, never mixed into `facts`. */
  untrustedText: string[];
}

export interface EvidenceBundleCompetitor {
  competitorId: string;
  competitorName: string;
  items: EvidenceBundleItem[];
}

export interface EvidenceBundle {
  period: {
    days: number;
    windowStart: string;
    windowEnd: string;
  };
  crossCompetitorContext: {
    aboveBaselineCount: number;
    totalTrackedCompetitors: number;
  };
  competitors: EvidenceBundleCompetitor[];
  /** Every ChangeEvent id present anywhere in `competitors[].items[].evidenceChangeEventIds` - the ONLY ids the model is allowed to cite (see validateDigestInterpretation.ts). */
  allowedEvidenceChangeEventIds: string[];
}

export const AI_HYPOTHESIS_CONFIDENCE_LEVELS = ["LOW", "MEDIUM"] as const;
export type AiHypothesisConfidence = (typeof AI_HYPOTHESIS_CONFIDENCE_LEVELS)[number];

/** A single observation/interpretation claim - always evidence-linked, never a bare assertion. */
export interface AiInterpretationClaim {
  text: string;
  evidenceChangeEventIds: string[];
}

export interface AiInterpretationHypothesis extends AiInterpretationClaim {
  confidence: AiHypothesisConfidence;
}

/**
 * Section 7/13 of the brief: the strict, structurally-distinguished
 * output contract. `observations` = FACT, `interpretations` =
 * INTERPRETATION, `hypotheses` = HYPOTHESIS (hedged, confidence-tagged).
 * No numeric confidence score anywhere (Section 13: "no 0.87/73%/8.4-10").
 */
export interface AiInterpretationOutput {
  summary: string;
  observations: AiInterpretationClaim[];
  interpretations: AiInterpretationClaim[];
  hypotheses: AiInterpretationHypothesis[];
}
